id: PBEAE9684
initial_creation_type: ocr
source_metadata:
  volumes:
    684d396be6ea4892873e28da54ed0a58:
      base_file: v116.txt
      image_group_id: I1PD95961
      title: སྨོན་ལམ་རིན་པོ་ཆེའི་རྒྱལ་པོ།
      total_pages: 1880
      volume_number: 116
